# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Bill DeRusha
tagline:          'dev et al'
description:      'Ideas & Projects'
url:              http://billderusha.com
baseurl:          

author:
  name:           'Bill DeRusha'
  url:            http://billderusha.com

paginate:         3

# Custom vars
version:          2.1.0
gems: [jekyll-paginate, jekyll-gist]

github:
  repo:           https://github.com/bderusha/billderusha
